config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'terms' => 'homes#terms'
  get 'contact' => 'homes#contact'
  get 'aboutus' => 'homes#aboutus'
  get "artists/search" => "artists#search"
  post 'artists/:id/follow' => 'artists#follow'
  post 'artists/:id/unfollow' => 'artists#unfollow'
  resources :artists
  resources :artists do
    resources :albums
  end

  get 'likes/index'
  get 'albums/' => 'albums#all_index'
  get 'albums/search' => 'albums#search'

  get 'posts' => 'posts#index'
  get 'posts/search' => 'posts#search'

  post 'artists/:artist_id/albums/:album_id/create' => "posts#create"
  post 'artists/:artist_id/albums/:album_id/:id/like' => "likes#create"
  post 'artists/:artist_id/albums/:album_id/:id/unlike' => "likes#destroy"
  post 'artists/:artist_id/albums/:album_id/:id/stock' => "stocks#create"
  post 'artists/:artist_id/albums/:album_id/:id/unstock' => "stocks#destroy"
  get 'artists/:artist_id/albums/:album_id/:id/edit' => 'posts#edit'
  post 'artists/:artist_id/albums/:album_id/:id/update' => "posts#update"
  post 'artists/:artist_id/albums/:album_id/:id/comment' => "posts#comment"
  post 'artists/:artist_id/albums/:album_id/:id/destroy' => "posts#destroy"
  get 'artists/:artist_id/albums/:album_id/new' => 'posts#new'
  get 'artists/:artist_id/albums/:album_id/:id' => 'posts#show'
  post 'artists/:artist_id/albums/:id/follow' => 'albums#follow'
  post 'artists/:artist_id/albums/:id/unfollow' => 'albums#unfollow'
  get 'artists/:artist_id/new' => 'posts#new'
  post 'artists/:artist_id/create' => "posts#create"
  get 'artists/:artist_id/:id' => 'posts#show'
  get 'artists/:artist_id/:id/edit' => 'posts#edit'
  post 'artists/:artist_id/:id/update' => "posts#update"
  post 'artists/:artist_id/:id/destroy' => "posts#destroy"
  post 'artists/:artist_id/:id/like' => 'likes#create'
  post 'artists/:artist_id/:id/unlike' => 'likes#destroy'
  post 'artists/:artist_id/:id/stock' => 'stocks#create'
  post 'artists/:artist_id/:id/unstock' => 'stocks#destroy'
  post 'artists/:artist_id/:id/comment' => 'posts#comment'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/users/sign_out' => 'devise/sessions#destroy'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/profile_edit' => 'users#profile_edit'
  post 'users/profile_update' => 'users#profile_update'
  post 'users/:id/follow' => 'users#follow'
  post 'users/:id/unfollow' => 'users#unfollow'
  get 'users/:id' => 'users#show'
  get 'users' => 'users#index'
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true
  has_many :albums, dependent: :destroy
  has_many :posts, dependent: :destroy
  def average_score
    (recieved_scores.sum(:score)/recieved_scores.count.to_f).round(2)
  end
  def recieved_scores
    posts.where.not(score: nil)
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy, :follow, :unfollow]
  before_action :sign_in_required, only: [:edit, :update, :destroy]

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artists_params)
    if @artist.save
      redirect_to @artist, notice: "登録完了"
    else
      render "new"
    end
  end

  def index
    @artists = Artist.all.order(name: "ASC")
    @artists = @artists.page(params[:page]).per(50)
  end

  def show
    @albums = @artist.albums
    @posts = @artist.posts.order(point: "DESC")
  end

  def edit
  end

  def update
    if @artist.update(artists_params)
      redirect_to @artist, notice: "変更完了"
    else
      render "edit"
    end
  end

  def search
    @artists = Artist.where("name LIKE ?", "%#{params[:word]}%").or(Artist.where("othername LIKE ?", "%#{params[:word]}%"))
    @artists = @artists.page(params[:page]).per(50)
    @word = params[:word]
  end

  def follow
    @follow = Follow.new(user_id: current_user.id, artist_id: @artist.id)
    @follow.save
  end

  def unfollow
    @follow = Follow.find_by(user_id: current_user.id, artist_id: @artist.id)
    @follow.destroy
  end
  
  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artists_params
    params.require(:artist).permit(:name, :othername, :tags, :apple, :wikipedia, :spotify, :bandcamp)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist_result.html.erb
<div class="row">
  <%= form_tag("/artists/search",:method => 'get') do %>
    <div class="col s10">
      <%= text_field_tag :word, "" ,placeholder: "(例)Little Richard", value: @word %>
    </div>
    <div class="col s2">
      <%= submit_tag '検索', :name => nil, class:"btn right" %>
    </div>
  <% end %>
</div>

<% @artists.each do |artist| %>
  <% if artist.average_score.nan? %>
    <% average_score = "-" %>
  <% else %>
    <% average_score = artist.average_score %>
  <% end %>
  <div class="section">
    <div class="row" style="margin-bottom: 0px;">
      <div class="col s4">
        <div class="img-parent">
          <div class="center img-child">
            <% if artist.imagelink %>
              <% if artist.imagelink.length != 0 %>
                    <img class="artist-img" src="<%= artist.imagelink %>">
              <% else %>
                <img class="artist-img" src="/assets/noimage.png">
              <% end %>
            <% else %>
              <img class="artist-img" src="/assets/noimage.png">
            <% end %>
          </div>
        </div>
      </div>
      <div class="col s8">
        <div style="padding-left: 3px;">
          <h6><%= link_to artist.name, artist %></h6><small>記事数: <%= artist.posts.count %> &nbsp; スコア: <%= average_score %>/10</small>
        </div>
      </div>
    </div>
  </div>
  <div class="divider"></div>
<% end %>
<div class="col s12">
  <div class="center">
    <%= paginate @artists %>
  </div>
</div>

app/views/artists/_card.html.erb
<div class="card">
	<div class="card-content">
		<p><% if post.album %><%= link_to post.album.name, artist_album_path(post.artist.id,post.album.id) %><br />/<% end %><%= link_to post.artist.name, artist_path(post.artist.id) %></p>
		<% if post.score %>
			<div class="right-align">スコア: <%= post.score %>/10</div>
		<% else %>
			<br />
		<% end %>
		<div class="card-title">
			<a href="<%=  post.post_path %>">
				<p class="black-text lighten-4">
					<%= post.summary %>
				</p>
			</a>
		</div>
		<div class="right-align">
			<% if current_user %>
				<% if current_user.id == post.user.id %>
					<a href=<%=  post.post_path + "/edit" %>>編集</a><br/>
				<% end %>
			<% end %>
			Reviewed by <strong><a href="/users/<%= post.user.id %>"><%= post.user.username %></a></strong>
		</div>
	</div>
	<div class="card-action bitsmall">
		<a></a>
		<span>
			<% if current_user %>
				<div id="like-<%= post.id %>" style="float:left;">
					<%= render partial: "like", locals: { post: post } %>
				</div>
				<div id="stock-<%= post.id %>" style="float:left;">
					<%= render partial: "stock", locals: { post: post } %>
				</div>
			<% end %>
			<% if post.comment_flg or post.content %>
				<div style="float:left;">
					<% if post.content.length != 0 %>
						<a href=<%=  post.post_path %> class="green-text">本文/コメント</a>
					<% elsif post.comment_flg %>
						<a href=<%=  post.post_path %>>コメント</a>
					<% end %>
				</div>
			<% end %>
			<% if post.blog_url.length != 0 %>
				<div style="float:left;">
					<a href="<%= post.blog_url %>" class="red-text">ブログを読む</a>
				</div>
			<% end %>
		</span>
	</div>
</div>

app/views/artists/_follow.html.erb
<% if current_user.already_artist_followed?(artist) %>
  <%= link_to 'フォロー中', "/artists/#{artist.id}/unfollow", method: :post, remote: true, class: "btn-flat mini-btn blue white-text" %>
<% else %>
  <%= link_to 'フォロー', "/artists/#{artist.id}/follow", method: :post, remote: true, class: "blue-text" %>
<% end %>

app/views/artists/_form.erb
<%= form_for(@artist) do |f| %>
  <% @artist.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
  <p>アーティスト名 [必須]</p>
  <%= f.text_field :name, placeholder:"(例)The Rolling Stones", class: "form-control" %>
  <p>別の読み方(英語、読み仮名、愛称など、カンマ区切り複数)</p>
  <%= f.text_field :othername, placeholder:"(例)ローリングストーンズ,ストーンズ", class: "form-control" %>
  <p>タグ(ジャンルなど)、カンマ区切り複数</p>
  <%= f.text_field :tags, placeholder:"(例)ロック,60s,ブルース", class: "form-control" %>
  <p>WikipediaのURL(任意)</p>
  <%= f.text_field :wikipedia , placeholder:"(例)https://ja.wikipedia.org/...", class: "form-control" %>
  <p>Apple Musicのシェアリンク(任意)</p>
  <%= f.text_field :apple, placeholder:"(例)https://music.apple.com/...", class: "form-control" %>
  <p>Spotifyのシェアリンク(任意)</p>
  <%= f.text_field :spotify, placeholder:"(例)https://open.spotify.com/...", class: "form-control" %>
  <p>bandcampのシェアリンク(任意)</p>
  <%= f.text_field :bandcamp, placeholder:"(例)http://xxx.bandcamp.com/...", class: "form-control" %>
  <%= f.submit "送信", class:"btn btn-secondary" %>
<% end %>

app/views/artists/_like.html.erb
<% if current_user.already_liked?(post) %>
  <%= link_to '評価済', post.post_path + "/unlike", method: :post, remote: true, class: "blue-grey-text" %>
<% else %>
  <%= link_to '評価⬆︎', post.post_path + "/like", method: :post, remote: true %>
<% end %>

app/views/artists/_stock.html.erb
<% if current_user.already_stocked?(post) %>
  <%= link_to '追加中', post.post_path + "unstock", method: :post, remote: true, class: "blue-grey-text" %>
<% else %>
  <%= link_to '後で読む', post.post_path + "stock", method: :post, remote: true %>
<% end %>

app/views/artists/edit.html.erb
<h5>アーティスト編集</h5>
<p>アーティスト:<%= @artist.name %></p>
<%= link_to "アルバムを追加", new_artist_album_path(@artist), class:"btn" %>
<br />
<br />
<div class="divider"></div>
<%= render 'form' %>

app/views/artists/follow.js.erb
$("#follow-artist-<%= @artist.id %>").html("<%= j(render partial: 'artists/follow', locals: { artist: @artist }) %>");

app/views/artists/index.html.erb
<h5>アーティスト一覧</h5>
<% if current_user %>
  <%= link_to "アーティストを追加", new_artist_path %>
<% end %>
<%= render 'artist_result'%>

app/views/artists/new.html.erb
<h5>新規アーティスト追加</h5>
<%= render 'form' %>

app/views/artists/search.html.erb
<h5>「<%= @word %>」のアーティスト検索結果</h5>
<% if current_user %>
  <%= link_to "アーティストを追加", new_artist_path %>
<% end %>
<%= render 'artist_result'%>

app/views/artists/show.html.erb
<% set_meta_tags title: "#{@artist.name}|オトハブ"  %>
<div class="row">
  <a href="/artists"><p>アーティスト</p></a>
  <div class="col s6 l4 center artist-show-img-container">
    <% if @artist.imagelink %>
      <img class="materialboxed" src="<%= @artist.imagelink %>" style="width: 80%;">
    <% else %>
      <img src="/assets/noimage.png" style="width: 80%;">
    <% end %>
  </div>
  <div class="col s6 l4">
    <div>
      <!-- a href="/artists"><p class="green-text">アーティスト</p></a-->
      <h5><%= @artist.name %></h5>
      <% if current_user %>
        <div id="follow-artist-<%= @artist.id %>">
          <%= render partial: "follow", locals: { artist: @artist } %>
        </div>
      <% end %>
      <% if @artist.average_score.nan? %>
        <% average_score = "-" %>
      <% else %>
        <% average_score = @artist.average_score %>
      <% end %>
      <p>Score: <%= average_score %>/10 &emsp;
        <% if current_user %>
          <%= link_to "編集", edit_artist_path %>
        <% end %>
      </p>
    </div>
    <div>
			<!-- Modal Trigger -->
			<a class="modal-trigger" href="#modal1" style="color: gray;"><i class="material-icons">info_outline</i></a>

			<!-- Modal Structure -->
			<div id="modal1" class="modal bottom-sheet">
				<div class="modal-content">
					<% if @artist.apple %>
            <% if @artist.apple.length != 0  %>
              <%= link_to "AppleMusic", @artist.apple, class: "btn-small pink lighten-2", style: "margin: 5px;" %>
            <% end %>
          <% end %>
          <% if @artist.spotify %>
            <% if @artist.spotify.length != 0  %>
              <%= link_to "Spotify", @artist.spotify, class: "btn-small light-green-text grey darken-3", style: "margin: 5px" %>
            <% end %>
          <% end %>
          <% if @artist.bandcamp %>
            <% if @artist.bandcamp.length != 0 %>
              <%= link_to "Bandcamp", @artist.bandcamp, class: "btn-small light-blue darken-3", style: "margin: 5px" %>
            <% end %>
          <% end %>
          <% if @artist.wikipedia %>
            <% if @artist.wikipedia.length != 0 %>
              <%= link_to "Wiki", @artist.wikipedia, class: "btn-small blue-grey lighten-5 black-text" %>
            <% end %>
          <% end %>
				</div>
			</div>
		</div>
  </div>
</div>
<div class="divider"></div>
<div class="section">
  <div class="row">
    <div class="col-12">
      <h6>アルバム(<%=  @artist.albums.count %>)
        <% if current_user %>
          <small> &emsp; <%= link_to "追加する", new_artist_album_path(@artist) %></small>
        <% end %>
      </h6>
      <div class="section">
        <div class="divider"></div>
        <% @artist.albums.each do |album| %>
          <div class="section">
            <div class="row" style="margin-bottom: 0px;">
              <div class="col s4">
                <div class="img-parent">
                  <div class="img-child center">
                    <% if album.imagelink %>
                      <% if album.imagelink.length != 0 %>
                          <img class="artist-img" src="<%= album.imagelink %>">
                      <% else %>
                        <img class="artist-img" src="/assets/noimage.png">
                      <% end %>
                    <% else %>
                      <img class="artist-img" src="/assets/noimage.png">
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="col s8">
                <h6>
                  <a href=<%=artist_album_path(@artist, album)%> class="collection-item">
                  <%= album.name %>
                  </a>
                </h6>
                <% if album.average_score.nan? %>
                  <% average_score = "-" %>
                <% else %>
                  <% average_score = album.average_score %>
                <% end %>
                <small>投稿数: <%= album.posts.count %> &emsp; スコア: <%= average_score %>/10</small>
              </div>
            </div>
          </div>
          <div class="divider"></div>
        <% end %>
      </div>
    </div>
    <br />
    <div class="col-12">
      <h6>このアーティストの投稿 &emsp; <%= link_to "投稿する", "/artists/#{@artist.id}/new", class: "btn-small" %></h6>
        <% @artist.posts.each do |post| %>
          <%= render partial: "/homes/card", locals: { post: post } %>
        <% end %>
    </div>
  </div>
</div>

app/views/artists/unfollow.js.erb
$("#follow-artist-<%= @artist.id %>").html("<%= j(render partial: 'artists/follow', locals: { artist: @artist }) %>");