config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'terms' => 'homes#terms'
  get 'contact' => 'homes#contact'
  get 'aboutus' => 'homes#aboutus'
  get "artists/search" => "artists#search"
  post 'artists/:id/follow' => 'artists#follow'
  post 'artists/:id/unfollow' => 'artists#unfollow'
  resources :artists
  resources :artists do
    resources :albums
  end

  get 'likes/index'
  get 'albums/' => 'albums#all_index'
  get 'albums/search' => 'albums#search'

  get 'posts' => 'posts#index'
  get 'posts/search' => 'posts#search'

  post 'artists/:artist_id/albums/:album_id/create' => "posts#create"
  post 'artists/:artist_id/albums/:album_id/:id/like' => "likes#create"
  post 'artists/:artist_id/albums/:album_id/:id/unlike' => "likes#destroy"
  post 'artists/:artist_id/albums/:album_id/:id/stock' => "stocks#create"
  post 'artists/:artist_id/albums/:album_id/:id/unstock' => "stocks#destroy"
  get 'artists/:artist_id/albums/:album_id/:id/edit' => 'posts#edit'
  post 'artists/:artist_id/albums/:album_id/:id/update' => "posts#update"
  post 'artists/:artist_id/albums/:album_id/:id/comment' => "posts#comment"
  post 'artists/:artist_id/albums/:album_id/:id/destroy' => "posts#destroy"
  get 'artists/:artist_id/albums/:album_id/new' => 'posts#new'
  get 'artists/:artist_id/albums/:album_id/:id' => 'posts#show'
  post 'artists/:artist_id/albums/:id/follow' => 'albums#follow'
  post 'artists/:artist_id/albums/:id/unfollow' => 'albums#unfollow'
  get 'artists/:artist_id/new' => 'posts#new'
  post 'artists/:artist_id/create' => "posts#create"
  get 'artists/:artist_id/:id' => 'posts#show'
  get 'artists/:artist_id/:id/edit' => 'posts#edit'
  post 'artists/:artist_id/:id/update' => "posts#update"
  post 'artists/:artist_id/:id/destroy' => "posts#destroy"
  post 'artists/:artist_id/:id/like' => 'likes#create'
  post 'artists/:artist_id/:id/unlike' => 'likes#destroy'
  post 'artists/:artist_id/:id/stock' => 'stocks#create'
  post 'artists/:artist_id/:id/unstock' => 'stocks#destroy'
  post 'artists/:artist_id/:id/comment' => 'posts#comment'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/users/sign_out' => 'devise/sessions#destroy'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/profile_edit' => 'users#profile_edit'
  post 'users/profile_update' => 'users#profile_update'
  post 'users/:id/follow' => 'users#follow'
  post 'users/:id/unfollow' => 'users#unfollow'
  get 'users/:id' => 'users#show'
  get 'users' => 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :following_users, through: :follows
  has_many :following_artists, class_name: 'Follow', foreign_key: :artist_id, dependent: :destroy
  has_many :following_albums, class_name: 'Follow', foreign_key: :album_id, dependent: :destroy
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  def already_stocked?(post)
    self.stocks.exists?(post_id: post.id)
  end
  def already_user_followed?(user)
    self.follows.exists?(following_user_id: user.id)
  end
  def already_artist_followed?(artist)
    self.follows.exists?(artist_id: artist.id)
  end
  def already_album_followed?(album)
    self.follows.exists?(album_id: album.id)
  end
  def already_album_posted?(album)
    self.posts.exists?(album_id: album.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def profile_edit
    @user = User.find_by(id: current_user.id)
  end

  def profile_update
    @user = User.find_by(id: current_user.id)
    user = params.permit(:profile, :blog_url, :twitter, :apple, :spotify)
    @user.update(user)
    flash[:notice] = "プロフィールを更新しました"
    redirect_to "/users/#{current_user.id}"
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def follow
    @user = User.find_by(id: params[:id])
    @follow = Follow.new(user_id: current_user.id, following_user_id: params[:id])
    @follow.save
  end

  def unfollow
    @user = User.find_by(id: params[:id])
    @follow = Follow.find_by(user_id: current_user.id, following_user_id: params[:id])
    @follow.destroy
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_card.html.erb
<div class="card">
	<div class="card-content">
		<p><% if post.album %><%= link_to post.album.name, artist_album_path(post.artist.id,post.album.id) %><br />/<% end %><%= link_to post.artist.name, artist_path(post.artist.id) %></p>
		<% if post.score %>
			<div class="right-align">スコア: <%= post.score %>/10</div>
		<% else %>
			<br />
		<% end %>
		<div class="card-title">
			<a href="<%=  post.post_path %>">
				<p class="black-text lighten-4">
					<%= post.summary %>
				</p>
			</a>
		</div>
		<div class="right-align">
			<% if current_user %>
				<% if current_user.id == post.user.id %>
					<a href=<%=  post.post_path + "/edit" %>>編集</a>
					<br />
				<% end %>
			<% end %>
			Reviewed by <strong><a href="/users/<%= post.user.id %>"><%= post.user.username %></a></strong>
		</div>
	</div>
	<div class="card-action bitsmall">
		<a></a>
		<span>
			<% if current_user %>
				<div id="like-<%= post.id %>-tab<%= tab %>" style="float:left;">
					<%= render partial: "like", locals: { post: post } %>
				</div>
				<div id="stock-<%= post.id %>-tab<%= tab %>" style="float:left;">
					<%= render partial: "stock", locals: { post: post } %>
				</div>
			<% end %>
			<% if post.comment_flg or post.content %>
				<div style="float:left;">
					<% if post.content.length != 0 %>
						<a href=<%=  post.post_path %> class="green-text">本文/コメント</a>
					<% elsif post.comment_flg %>
						<a href=<%=  post.post_path %>>コメント</a>
					<% end %>
				</div>
			<% end %>
			<% if post.blog_url.length != 0 %>
				<div style="float:left;">
					<a href="<%= post.blog_url %>" class="red-text">ブログを読む</a>
				</div>
			<% end %>
		</span>
	</div>
</div>

app/views/users/_follow.html.erb
<% if current_user.already_user_followed?(user) %>
  <%= link_to 'フォロー中', "/users/#{user.id}/unfollow", method: :post, remote: true, class: "btn-flat mini-btn blue white-text" %>
<% else %>
  <%= link_to 'フォロー', "/users/#{user.id}/follow", method: :post, remote: true, class: "blue-text" %>
<% end %>

app/views/users/_like.html.erb
<% if current_user.already_liked?(post) %>
  <%= link_to '評価済', post.post_path + "unlike", method: :post, remote: true, class: "blue-grey-text" %>
<% else %>
  <%= link_to '評価⬆︎', post.post_path + "like", method: :post, remote: true %>
<% end %>

app/views/users/_stock.html.erb
<% if current_user.already_stocked?(post) %>
  <%= link_to '追加中', post.post_path + "unstock", method: :post, remote: true, class: "blue-grey-text" %>
<% else %>
  <%= link_to '後で読む', post.post_path + "stock", method: :post, remote: true %>
<% end %>

app/views/users/follow.js.erb
$("#follow-user-<%= @user.id %>").html("<%= j(render partial: 'users/follow', locals: { user: @user }) %>");

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/profile_edit.html.erb
<h5>プロフィール編集</h5>
<%= form_with url:"/users/profile_update", local: true do |f| %>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
  <br />
  <p>プロフィール文</p>
  <%= f.text_field :profile, placeholder:"(例)60年代のロックが好きです!", class: "form-control", value: @user.profile %>
  <p>ブログURL</p>
  <%= f.text_field :blog_url, placeholder:"(例)https://...", class: "form-control", value: @user.blog_url %>
  <p>Twitter ID</p>
  <%= f.text_field :twitter, placeholder:"(例)@xxxxxx", class: "form-control", value: @user.twitter %>
  <p>Apple Music ID</p>
  <%= f.text_field :apple, placeholder:"(例)@xxxxxx", class: "form-control", value: @user.apple %>
  <p>Spotify シェアリンク</p>
  <%= f.text_field :spotify, placeholder:"(例)https://...", class: "form-control", value: @user.spotify %>
  <%= f.submit "送信", class:"btn btn-secondary" %>
<% end %>

app/views/users/show.html.erb
<script>
  $(document).ready(function(){
    $('.tabs').tabs();
  });
</script>

<% set_meta_tags title: "#{@user.username} USER PAGE|オトハブ"  %>

<h5 class="center-align"><%= @user.username %></h5>
<div class="center">
  <% if current_user %>
    <% if current_user.id == @user.id %>
      <%= link_to 'アカウント設定', edit_user_registration_path %>
      <%= link_to "プロフィール編集", "/users/profile_edit" %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <br />
    <% else %>
      <div id="follow-user-<%= @user.id %>">
        <%= render partial: "follow", locals: { user: @user } %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="center">
  <% if @user.blog_url %>
    <% if @user.blog_url.length != 0 %>
      <br />
      <a href="<%= @user.blog_url %>" class="btn-small red">ブログを見る</a>
    <% end %>
  <% end %>
</div>
<br />
<div class="divider"></div>
<p class="center"><%= @user.profile %></p>
<div class="center">
<% if @user.twitter %>
  <% if @user.twitter.length != 0 %>
    <a href="<%= "https://twitter.com/#{@user.twitter.gsub("@","")}" %>" class="btn-small blue">Twitter</a>
  <% end %>
<% end %>
<% if @user.apple %>
  <% if @user.apple.length != 0 %>
    <a href="<%= "https://music.apple.com/profile/#{@user.apple.gsub("@","")}" %>" class="btn-small pink lighten-2">AppleMusic</a>
  <% end %>
<% end %>
<% if @user.spotify %>
  <% if @user.spotify.length != 0 %>
    <a href="<%= @user.spotify %>" class="btn-small light-green-text grey darken-3">Spotify</a>
  <% end %>
<% end %>
</div>
<br />
<div class="divider"></div>
<div class="row">
  <% if current_user %>
    <% if current_user.id == @user.id %>
      <div class="col s12">
        <ul class="tabs">
          <li class="tab col s3"><a href="#test1">TL</a></li>
          <li class="tab col s3"><a href="#test2">後で読む</a></li>
          <li class="tab col s3"><a href="#test3">評価済み</a></li>
          <li class="tab col s3"><a href="#test4">投稿</a></li>
        </ul>
      </div>
      <div id="test1" class="col s12">
        <% tl_posts = Post.where(user_id: current_user.following_user_ids).or(Post.where(artist_id: current_user.following_artist_ids).or(Post.where(album_id: current_user.following_album_ids).or(Post.where(user_id: current_user.id)))) %>
        <% tl_posts = tl_posts.order(created_at: :desc) %>
        <% tl_posts.each do |post| %>
          <%= render partial: "card", locals: { post: post, tab: 1 } %>
        <% end %>
      </div>
      <div id="test2" class="col s12">
        <% Stock.where(user_id: current_user.id).order(created_at: :desc).each do |stock| %>
          <% post = stock.post %>
          <%= render partial: "card", locals: { post: post, tab: 2 } %>
        <% end %>
      </div>
      <div id="test3" class="col s12">
        <% Like.where(user_id: current_user.id).order(created_at: :desc).each do |like| %>
          <% post = like.post %>
          <%= render partial: "card", locals: { post: post, tab: 3 } %>
        <% end %>
      </div>
    <% else %>
      <p class="center">投稿一覧</p>
    <% end %>
  <% else %>
      <p class="center">投稿一覧</p>
  <% end %>
  <div id="test4" class="col s12">
    <% @user.posts.order(created_at: "DESC").each do |post| %>
      <%= render partial: "card", locals: { post: post, tab: 4 } %>
    <% end %>
  </div>
</div>

app/views/users/unfollow.js.erb
$("#follow-user-<%= @user.id %>").html("<%= j(render partial: 'users/follow', locals: { user: @user }) %>");