config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'terms' => 'homes#terms'
  get 'contact' => 'homes#contact'
  get 'aboutus' => 'homes#aboutus'
  get "artists/search" => "artists#search"
  post 'artists/:id/follow' => 'artists#follow'
  post 'artists/:id/unfollow' => 'artists#unfollow'
  resources :artists
  resources :artists do
    resources :albums
  end

  get 'likes/index'
  get 'albums/' => 'albums#all_index'
  get 'albums/search' => 'albums#search'

  get 'posts' => 'posts#index'
  get 'posts/search' => 'posts#search'

  post 'artists/:artist_id/albums/:album_id/create' => "posts#create"
  post 'artists/:artist_id/albums/:album_id/:id/like' => "likes#create"
  post 'artists/:artist_id/albums/:album_id/:id/unlike' => "likes#destroy"
  post 'artists/:artist_id/albums/:album_id/:id/stock' => "stocks#create"
  post 'artists/:artist_id/albums/:album_id/:id/unstock' => "stocks#destroy"
  get 'artists/:artist_id/albums/:album_id/:id/edit' => 'posts#edit'
  post 'artists/:artist_id/albums/:album_id/:id/update' => "posts#update"
  post 'artists/:artist_id/albums/:album_id/:id/comment' => "posts#comment"
  post 'artists/:artist_id/albums/:album_id/:id/destroy' => "posts#destroy"
  get 'artists/:artist_id/albums/:album_id/new' => 'posts#new'
  get 'artists/:artist_id/albums/:album_id/:id' => 'posts#show'
  post 'artists/:artist_id/albums/:id/follow' => 'albums#follow'
  post 'artists/:artist_id/albums/:id/unfollow' => 'albums#unfollow'
  get 'artists/:artist_id/new' => 'posts#new'
  post 'artists/:artist_id/create' => "posts#create"
  get 'artists/:artist_id/:id' => 'posts#show'
  get 'artists/:artist_id/:id/edit' => 'posts#edit'
  post 'artists/:artist_id/:id/update' => "posts#update"
  post 'artists/:artist_id/:id/destroy' => "posts#destroy"
  post 'artists/:artist_id/:id/like' => 'likes#create'
  post 'artists/:artist_id/:id/unlike' => 'likes#destroy'
  post 'artists/:artist_id/:id/stock' => 'stocks#create'
  post 'artists/:artist_id/:id/unstock' => 'stocks#destroy'
  post 'artists/:artist_id/:id/comment' => 'posts#comment'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/users/sign_out' => 'devise/sessions#destroy'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/profile_edit' => 'users#profile_edit'
  post 'users/profile_update' => 'users#profile_update'
  post 'users/:id/follow' => 'users#follow'
  post 'users/:id/unfollow' => 'users#unfollow'
  get 'users/:id' => 'users#show'
  get 'users' => 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :summary, presence: true, length: { maximum: 140 }
  belongs_to :user
  belongs_to :artist
  belongs_to :album, optional: true
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :stocks, dependent: :destroy
  validates :content, presence: false
  def post_path
    if album_id.present?
      return "/artists/#{artist.id}/albums/#{album.id}/#{id}/"
    else
      return "/artists/#{artist.id}/#{id}/"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :sign_in_required, only: [:new, :edit, :update, :destroy, :comment]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
    @posts = @posts.all.order(created_at: :desc)
    @posts = @posts.page(params[:page]).per(10)
  end

  def search
    @word = params[:word]
    @posts = Post.where("summary LIKE ?", "%#{params[:word]}%").or(Post.where("content LIKE ?", "%#{params[:word]}%"))
    @posts = @posts.all.order(created_at: :desc)
    @posts = @posts.page(params[:page]).per(10)
  end

  def ensure_correct_user
    if current_user.id != Post.find_by(id: params[:id]).user_id
      redirect_to("/")
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @artist = @post.artist
    @album = @post.album
  end

  def new
    @post = Post.new
    if params[:album_id]
      @album = Album.find(params[:album_id])
      @artist = Artist.find(params[:artist_id])
    elsif params[:artist_id]
      @artist = Artist.find(params[:artist_id])
    end
  end

  def create
    if params[:score] == "nil"
      score = nil
    else
      score = params[:score]
    end
    if Post.find_by(user_id: params[:user_id], album_id: params[:album_id])
      redirect_to("/")
      return
    end
    @post = Post.new(
      summary: params[:summary],
      content: params[:content],
      user_id: params[:user_id],
      blog_url: params[:blog_url],
      score: score,
      album_id: params[:album_id],
      artist_id: params[:artist_id],
      html: params[:html]
    )
    if @post.save
      flash[:notice] = "投稿しました"
      if params[:album_id]
        redirect_to("/artists/#{params[:artist_id]}/albums/#{params[:album_id]}")
      else
        redirect_to("/artists/#{params[:artist_id]}")
      end
    else
      if params[:album_id]
        @album = Album.find_by(id: params[:album_id])
        @artist = Artist.find_by(id: params[:artist_id])
        render :new
      else
        @artist = Artist.find_by(id: params[:artist_id])
        render :new
      end
    end
  end

  def edit
    if params[:album_id]
      @album = Album.find_by(id: params[:album_id])
      @artist = Artist.find_by(id: params[:artist_id])
    else
      @artist = Artist.find_by(id: params[:artist_id])
    end
    @post = Post.find_by(id: params[:id])
  end

  def update
    if params[:score] == "nil"
      score = nil
    else
      score = params[:score]
    end
    @post = Post.find_by(id: params[:id])
    if @post.update(
      summary: params[:summary],
      content: params[:content],
      user_id: params[:user_id],
      blog_url: params[:blog_url],
      score: score,
      album_id: params[:album_id],
      artist_id: params[:artist_id],
      html: params[:html]
    )
      flash[:notice] = "投稿を更新しました"
      if params[:album_id]
        redirect_to("/artists/#{params[:artist_id]}/albums/#{params[:album_id]}")
      else
        redirect_to("/artists/#{params[:artist_id]}")
      end
    else
      if params[:album_id]
        @album = Album.find_by(id: params[:album_id])
        @artist = Artist.find_by(id: params[:artist_id])
        render :edit
      else
        @artist = Artist.find_by(id: params[:artist_id])
        render :edit
      end
    end
  end

  def comment
    @comment = Comment.new(
      user_id: current_user.id,
      post_id: params[:id],
      text: params[:text]
    )
    if @comment.save
      flash[:notice] = "コメントを投稿しました"
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = "コメント投稿失敗"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if params[:album_id]
      redirect_path = "/artists/#{params[:artist_id]}/albums/#{params[:album_id]}"
    else
      redirect_path = "/artists/#{params[:artist_id]}"
    end
    @post.destroy
    respond_to do |format|
      format.html { redirect_to redirect_path , notice: '削除しました' }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_card.html.erb
<div class="card">
	<div class="card-content">
		<p><% if post.album %><%= link_to post.album.name, artist_album_path(post.artist.id,post.album.id) %><br />/<% end %><%= link_to post.artist.name, artist_path(post.artist.id) %></p>
		<% if post.score %>
			<div class="right-align">スコア: <%= post.score %>/10</div>
		<% else %>
			<br />
		<% end %>
		<div class="card-title">
			<a href="<%=  post.post_path %>">
				<p class="black-text lighten-4">
					<%= post.summary %>
				</p>
			</a>
		</div>
		<div class="right-align">
			<% if current_user %>
				<% if current_user.id == post.user.id %>
					<a href=<%=  post.post_path + "/edit" %>>編集</a><br />
				<% end %>
			<% end %>
			Reviewed by <strong><a href="/users/<%= post.user.id %>"><%= post.user.username %></a></strong>
		</div>
	</div>
	<div class="card-action bitsmall">
		<a></a>
		<span>
			<% if current_user %>
				<div id="like-<%= post.id %>" style="float:left;">
					<%= render partial: "homes/like", locals: { post: post } %>
				</div>
				<div id="stock-<%= post.id %>" style="float:left;">
					<%= render partial: "homes/stock", locals: { post: post } %>
				</div>
			<% end %>
			<% if post.comment_flg or post.content %>
				<div style="float:left;">
					<% if post.content.length != 0 %>
						<a href=<%=  post.post_path %> class="green-text">本文/コメント</a>
					<% elsif post.comment_flg %>
						<a href=<%=  post.post_path %>>コメント</a>
					<% end %>
				</div>
			<% end %>
			<% if post.blog_url.length != 0 %>
				<div style="float:left;">
					<a href="<%= post.blog_url %>" class="red-text">ブログを読む</a>
				</div>
			<% end %>
		</span>
	</div>
</div>

app/views/posts/_likebtn.html.erb
<% if current_user.already_liked?(post) %>
  <%= link_to '評価済', post.post_path + "unlike", method: :post, remote: true, class: "blue-grey btn-small" %>
<% else %>
  <%= link_to '評価⬆︎', post.post_path + "like", method: :post, remote: true, class: "btn-small orange" %>
<% end %>

app/views/posts/_post_result.html.erb
<div class="row">
  <%= form_tag("/posts/search",:method => 'get') do %>
    <div class="col s10">
    <%= text_field_tag :word, "" ,placeholder: "(例)Beatles", value: "#{@word}" %>
    </div>
    <div class="col s2">
      <%= submit_tag '検索', :name => nil, class:"btn right" %>
    </div>
  <% end %>
</div>
<div class="col s12">
  <% @posts.each do |post| %>
    <div>
    <%= render partial: "card", locals: { post: post } %>
    </div>
  <% end %>
</div>
<div class="col s12">
  <div class="center">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/_stockbtn.html.erb
<% if current_user.already_stocked?(post) %>
  <%= link_to '追加中', post.post_path + "unstock", method: :post, remote: true, class: "blue-grey btn-small" %>
<% else %>
  <%= link_to '後で読む', post.post_path + "stock", method: :post, remote: true, class: "btn-small blue" %>
<% end %>

app/views/posts/edit.html.erb
<script>
	$(document).ready(function() {
    	$('textarea#textarea2').characterCounter();
  	});
</script>
<h5>記事編集</h5>

<% if @album %>
	<%= @album.name %> /
	<% update_path = "/artists/#{@artist.id}/albums/#{@album.id}/#{@post.id}/update" %>
	<% destroy_path = "/artists/#{@artist.id}/albums/#{@album.id}/#{@post.id}/destroy" %>
<% else %>
	<% update_path = "/artists/#{@artist.id}/#{@post.id}/update" %>
	<% destroy_path = "/artists/#{@artist.id}/#{@post.id}/destroy" %>
<% end %>
<%= @artist.name %>

<%= form_tag(update_path, method: :post) do %>
  <% @post.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
	<p>サマリー (140字以内) [必須]</p>
	<div class="input-field col s6">
		<textarea name="summary" placeholder="(例)このアルバムで特筆すべきはビルワイマンの生み出す、唯一無二のグルーブである" id="textarea2" class="materialize-textarea" data-length="140"><%= @post.summary %></textarea>
	</div>
	<p>ブログURL(任意)</p>
	<textarea name="blog_url" placeholder="(例)http://www...." class="materialize-textarea"><%= @post.blog_url %></textarea>
	<br/>
	<p>得点(10点満点、任意)</p>
	<select name="score" class="browser-default">
		<option value="nil">-</option>
		<% for num in 0..10 do %>
			<% if @post.score == num %>
				<option value="<%= num %>" selected><%= num %></option>
			<% else %>
				<option value="<%= num %>"><%= num %></option>
			<% end %>
		<% end %>
	</select>
	<p>レビュー本文(任意、100字以上)</p>
	<textarea name="content" class="materialize-textarea"><%= @post.content %></textarea>
	<input type="hidden" name="public" value="true">
	<input type="hidden" name="comment_flg" value="true">
	<input type="hidden" name="user_id" value="<%= current_user.id %>">
	<% if @album %>
		<input type="hidden" name="album_id" value="<%= @album.id %>">
	<% end %>
	<input type="hidden" name="artist_id" value="<%= @artist.id %>">
	<p>本文のフォーマット</p>
	<select name="html" id="html">
	<% if @post.html %>
		<option value="false">テキスト(標準)</option>
		<option value="true" selected>HTML</option>
	<% else %>
		<option value="false" selected>テキスト(標準)</option>
		<option value="true">HTML</option>
	<% end %>
	</select>
	<input type="submit" class="btn" value="送信">
<% end %>
<br />
<br />
<%= link_to "投稿を削除", destroy_path, method: :post, class: "btn-small red", data: { confirm: "投稿を削除しますか？(投稿内容、コメントは元に戻せません)" } %>

app/views/posts/index.html.erb
<h5>新着投稿一覧</h5>
<%= render 'post_result' %>

app/views/posts/new.html.erb
<script>
	$(document).ready(function() {
    	$('textarea#textarea2').characterCounter();
  	});
</script>
<h5>
	<% if @album %>
		<%= @album.name %> /
		<% create_path = "/artists/#{@artist.id}/albums/#{@album.id}/create" %>
	<% else %>
		<% create_path = "/artists/#{@artist.id}/create" %>
	<% end %>
	<%= @artist.name %>
</h5>
<% if not @album %>
	<p class="red-text">
		<small>※これはアーティストレビューの投稿ページです。アルバムレビューの投稿はアルバムのページから行ってください。</small>
	</p>
<% end %>
<h5>ブログ登録/レビュー</h5>

<%= form_tag(create_path, method: :post) do %>
  <% @post.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
	<p>サマリー (140字以内) [必須]</p>
	<div class="input-field col s6">
		<textarea name="summary" placeholder="(例)このアルバムで特筆すべきはビルワイマンの生み出す、唯一無二のグルーブである" id="textarea2" class="materialize-textarea" data-length="140"><%= @post.summary %></textarea>
	</div>
	<p>ブログURL(任意)</p>
	<input name="blog_url" placeholder="(例)http://www...."><%= @post.blog_url %></input>
	<% if @album %>
		<br/>
		<p>得点(10点満点、任意)</p>
		<select name="score" class="browser-default">
			<option value="nil">-</option>
			<option value="0">0</option>
			<option value="1">1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
			<option value="6">6</option>
			<option value="7">7</option>
			<option value="8">8</option>
			<option value="9">9</option>
			<option value="10">10</option>
		</select>
	<% end %>
	<p>レビュー本文(任意)</p>
	<textarea name="content" class="materialize-textarea"><%= @post.content %></textarea>
	<input type="hidden" name="public" value="true">
	<input type="hidden" name="comment_flg" value="true">
	<input type="hidden" name="user_id" value="<%= current_user.id %>">
	<% if @album %>
		<input type="hidden" name="album_id" value="<%= @album.id %>">
	<% else %>
		<input type="hidden" name="artist_id" value="<%= @artist.id %>">
	<% end %>
	<p>本文のフォーマット</p>
	<select name="html" id="html">
	<option value="false">テキスト(標準)</option>
	<option value="true">HTML</option>
	</select>
	<input type="submit" class="btn" value="送信">
<% end %>

app/views/posts/search.html.erb
<h5>「<%= @word %>」の投稿検索結果</h5>
<%= render 'post_result' %>

app/views/posts/show.html.erb
 <style>
  .share {
    height: 22px;
    line-height: 22px;
    font-size: 11px;
    padding: 0 2px;
    margin: 1.5px 0 0 0;
    border-radius: 3px;
  }
  img {
      width:auto;
      height:auto;
      max-width:100%;
      max-height:100%;
      padding: 1.5px 1.5px;
  }
</style>
<div class="row">
  <div class="col s12">
    <% if @album %>
      <h6><%= link_to @post.album.name, "/artists/#{@post.artist.id}/albums/#{@post.album.id}" %> / <%= link_to @post.artist.name, "/artists/#{@post.artist.id}" %></h6>
      <% set_meta_tags title: "#{@post.album.name}/#{@post.artist.name} Reviewed by #{@post.user.username}|オトハブ"  %>
      <% set_meta_tags canonical: "https://otohub.tokyo/artists/#{@post.artist.id}/albums/#{@post.album.id}/#{@post.id}" %>
    <% else %>
      <h6><%= link_to @post.artist.name, "/artists/#{@post.artist.id}" %></h6>
      <% set_meta_tags title: "#{@post.artist.name} Reviewed by #{@post.user.username}|オトハブ"  %>
      <% set_meta_tags canonical: "https://otohub.tokyo/artists/#{@post.artist.id}/#{@post.id}" %>
    <% end %>
  </div>
  <div class="col s12 l7">

    <% set_meta_tags description: "オトハブ Review|#{@post.summary}"  %>

    <div class="col s12">
      <% if @post.score %>
        <span class="right">スコア: <%= @post.score %>/10</span>
      <% else %>
        <span class="blue-grey-text right">スコア: -/10</span>
      <% end %> 
    </div>
    <br />
    <h5><%= @post.summary %></h5>
    <div class="col s12">
      <% if current_user %>
        <% if current_user.id == @post.user.id %>
          <% if @album %>
            <a href=<%= "/artists/#{@artist.id}/albums/#{@album.id}/#{@post.id}/edit" %> class="right">編集する</a>
          <% else %>
            <a href=<%= "/artists/#{@artist.id}/#{@post.id}/edit" %> class="right">編集する</a>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="col s12">
      <h6 class="right">Reviewed by <%= link_to @post.user.username, "/users/#{@post.user.id}" %></h6>
    </div>
    <div class="col s12">
      <div class="divider"></div>
      <% if @post.html %>
        <span class="bitlarge"><p><%= @post.content.html_safe %></p></span>
      <% else %>
        <span class="bitlarge"><p><%= raw Rinku.auto_link(simple_format(@post.content), :all, 'target="_blank"') %></p></span>
      <% end %>
      <br />
      <% if current_user %>
        <div id="likebtn-<%= @post.id %>" style="float:left;">
          <%= render partial: "likebtn", locals: { post: @post } %>
        </div>
        <div style="float:left;">
          &nbsp; &nbsp;
        </div>
        <div id="stockbtn-<%= @post.id %>" style="float:left;" style="mergin-left">
          <%= render partial: "stockbtn", locals: { post: @post } %>
        </div>
        <div style="float:left;">
          &nbsp; &nbsp;
        </div>
      <% end %>
      <% if @post.blog_url.length != 0 %>
        <a href="<%= @post.blog_url %>" class="red btn-small">ブログを読む</a>
      <% end %>
      <% if current_user %>
        <br />
      <% end %>
      <br />
      <br />
      <div class="left">
        <% if @album %>
          <% tweet_content = "#{@post.album.name}/#{@post.artist.name} Reviewed by #{@post.user.username}|オトハブ" %>
        <% else %>
          <% tweet_content = "#{@post.artist.name} Reviewed by #{@post.user.username}|オトハブ" %>
        <% end %>
        <div class="left">
          <a href="https://twitter.com/share?url=<%= request.url %>&text=<%= tweet_content.truncate(100) %>" rel="nofollow" target="_blank" class="btn-small light-blue share z-depth-1"><img src="/assets/Twitter_Social_Icon_Circle_White.png"><div class="share-text right">tweet</div></a>
        </div>
        <% if false %>
          <a href="https://twitter.com/share?ref_src=twsrc%5Etfw<%= request.url %>&text=<%= tweet_content.truncate(100) %>" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          <a href="https://twitter.com/share?url=<%= request.url %>&text=<%= tweet_content.truncate(100) %>" class="btn-small light-blue share"><img src="/assets/Twitter_Social_Icon_Circle_White.png"><div class="share-text right">tweet</div></a>
          <%#&text=#{tweet_content.truncate(100)}", class: 'btn-small light-blue share', data: { show_count: false }, title: "ぴえん。", target: '_blank' %>
          <%#= javascript_include_tag 'https://platform.twitter.com/widgets.js', charset: 'utf-8', async: true %>
        <% end %>
        
      </div>
      <div style="float:left;">
        &nbsp; &nbsp;
      </div>
      <div class="left">
        <a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.url %>" class="btn-small blue share"><img src="/assets/f_logo_RGB-White_58.png"><div class="share-text right">シェア</div></a>
      </div>
      <div style="float:left;">
        &nbsp; &nbsp;
      </div>
      <div class="left">
        <textarea id="js-copytext" style="display:none;font-size:16px;position:fixed;left:100vw" readonly=readonly><%= request.url %></textarea>
        <button type="button" id="js-copybtn" class="btn-small grey share">リンクをコピー</button>
      </div>
      <br />
      <br />
    </div>
  </div>
  <div class="col s12 l1">
    <br />
  </div>
  <div class="col s12 l4">
    <% if @album %>
      <p>このアルバムを聴く</p>
    <div class="divider"></div>
      <br />
      <% if @album.apple %>
        <% if @album.apple.length != 0 %>
          <iframe allow="autoplay *; encrypted-media *;" frameborder="0" height=300" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="<%= @album.apple.sub("music.apple.com","embed.music.apple.com") %>"></iframe>
        <% end %>
      <% end %>
      <% if @album.spotify %>
        <% if @album.spotify.length != 0  %>
          <%= link_to "Spotify", @album.spotify, class: "btn-small light-green-text grey darken-3" %>
        <% end %>
      <% end %>
      <% if @album.bandcamp %>
        <% if @album.bandcamp.length != 0 %>
          <%= link_to "Bandcamp", @album.bandcamp, class: "btn-small light-blue darken-3" %>
        <% end %>
      <% end %>
      <% if @album.wikipedia %>
        <% if @album.wikipedia.length != 0 %>
          <%= link_to "Wiki", @album.wikipedia, class: "btn-small blue-grey lighten-5 black-text" %>
        <% end %>
      <% end %>
    <% end %>
    <br />
    <% if @post.comment_flg %>
      <p>コメント欄</p>
      <div class="divider"></div>
      <% @post.comments.each do |comment| %>
        <div class="container">
          <div class="row">
            <div class="col s12">
              <p><%= comment.text %></p>
            </div>
            <div class="col s12">
              <small class="right">Commented by <%= link_to comment.user.username, "/users/#{comment.user.id}" %></small>
            </div>
          </div>
        </div>
        <div class="divider"></div>
      <% end %>
      <br />
      <% if @album %>
        <% comment_path = "/artists/#{@post.artist.id}/albums/#{@post.album.id}/#{@post.id}/comment" %>
      <% else %>
        <% comment_path = "/artists/#{@post.artist.id}/#{@post.id}/comment" %>
      <% end %>
      <%= form_tag(comment_path) do %>
        <textarea name="text" class="materialize-textarea" placeholder="コメント"></textarea>
        <br/>
        <input type="submit" value="コメントを投稿" class="btn">
      <% end %>
    <% end %>
  </div>
</div>